repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.4 # Use the latest stable release
    hooks:
      - id: ruff
        name: ruff-lint
      - id: ruff-format
        name: ruff-format
